### ISSUE TITLE
Migrate to Reanimated for performance gain.

### ISSUE THREAD

**Issue by ali-thowfeek** [chramos/react-native-skeleton-placeholder#74]
Hi, with the current version of this package my app in production shows an extreme lag where there is a skeleton loader. I believe instead of the `Animated` Api of React Native, if we use Reanimated2, we can achieve a much better performance. I haven't tried this though. In my free time I'm thinking of giving this a shot.

**Comment by chramos** [comment]
for sure, I'll implement a new version with Reanimated, I'll try to add support to v1 and v2

**Comment by chramos** [comment]
my concern is the number of dependencies required to use this library, currently we have:
masked-view
linear-gradient

and now the plan is to add a new one: reanimated

do you think is it ok? 
let me know what you think about it

**Comment by ali-thowfeek** [comment]
Hi @chramos I did a little testing with reanimated 2. I didn't see a performance boost at all. Although my testing was not an accurate one, if it doesn't give a performance boost then no point in adding another dependency.

**Comment by chramos** [comment]
hey, @ali-thowfeek  since we are using a translateX animation we are using to useNativeDriver, I think we'll not see a big difference changing to the reanimated library.
I'm doing some tests to try to improve the library performance.
Can you provide me an example of how you're using it in your production app to get a slow performance?

**Comment by ali-thowfeek** [comment]
Hey @chramos Sorry I'm no longer able to share the implementation. I'll close this issue for now as I don't have any input in this.
